apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - grafana.yaml
  - datasources.yaml
  - agentgateway-dashboard.yaml
  - agentgateway-resources.yaml
  - mcp-dashboard.yaml
