apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: model-provider
  namespace: agentgateway-system
spec:
  parentRefs:
    - name: kagent-model-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1
      backendRefs:
        - group: agentgateway.dev
          kind: AgentgatewayBackend
          name: model-provider
